export const RideOptionsTheme = {
  background: '#FFFFFF',
  card: '#FFFFFF',
  cardMuted: '#F3EBE0',
  primary: '#6E4424',
  primaryDark: '#4A2E18',
  accent: '#B8895A',
  border: '#ECE3D8',
  text: '#2D241D',
  textSecondary: '#7A7068',
  success: '#2E7D4F',
  successBg: '#E8F5EE',
  surge: '#EA580C',
  surgeBg: '#FFF7ED',
  radiusSheet: 32,
  radiusCard: 20,
  radiusButton: 18,
  shadow: {
    shadowColor: '#2D241D',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 16,
  },
} as const;
