import { palette } from '../../config/theme';
export const RideOptionsTheme = {
  background: palette.surface,
  card: palette.surface,
  cardMuted: palette.background,
  primary: palette.primary,
  primaryDark: palette.primaryDark,
  accent: palette.textSecondary,
  border: palette.border,
  text: palette.text,
  textSecondary: palette.textSecondary,
  success: palette.success,
  successBg: palette.successSoft,
  surge: palette.warning,
  surgeBg: palette.warningSoft,
  radiusSheet: 32,
  radiusCard: 20,
  radiusButton: 18,
  shadow: {
    shadowColor: palette.text,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.12,
    shadowRadius: 24,
    elevation: 16,
  },
} as const;
