export const palette = {
  primary: '#111111',
  primaryDark: '#000000',
  primaryLight: '#2A2A2A',
  background: '#F7F6F2',
  surface: '#FFFFFF',
  text: '#111111',
  textSecondary: '#6B6B6B',
  onPrimary: '#FFFFFF',
  disabledButtonBg: '#E8E8ED',
  disabledButtonFg: '#6B6B6B',
  border: '#E2E0DB',
  success: '#111111',
  successSoft: '#F2F2F2',
  error: '#C94A4A',
  errorSoft: '#FBEAEA',
  warning: '#B57C1E',
  warningSoft: '#F8F0E1',
} as const;

const sharedTokens = {
  primary: palette.primary,
  primaryDark: palette.primaryDark,
  primaryLight: palette.primaryLight,
  buttonText: palette.onPrimary,
  onPrimary: palette.onPrimary,
  disabledButtonBg: palette.disabledButtonBg,
  disabledButtonFg: palette.disabledButtonFg,
  secondary: palette.textSecondary,
  secondaryDark: palette.primaryDark,
  accent: palette.primary,
  accentDark: palette.primaryDark,
  accentSoft: palette.primaryLight,
  accentBorder: palette.border,
  primarySoft: 'rgba(0, 0, 0, 0.1)',
  secondarySoft: 'rgba(0, 0, 0, 0.05)',
  cyan: palette.primaryLight,
  green: palette.success,
  orange: palette.textSecondary,
  gold: palette.primaryLight,
  goldDark: palette.primaryDark,
  goldLight: palette.primaryLight,
  goldHighlight: palette.primaryDark,
  highlight: palette.primaryLight,
  success: palette.success,
  warning: palette.warning,
  danger: palette.error,
  error: palette.error,
  dangerSoft: palette.errorSoft,
  successSoft: palette.successSoft,
  warningSoft: palette.warningSoft,
  white: palette.surface,
  text: palette.text,
  textSecondary: palette.textSecondary,
  textMuted: palette.textSecondary,
  border: palette.border,
  borderLight: palette.border,
  borderSoft: palette.border,
  borderFocus: palette.primary,
  borderError: palette.error,
  hiddenGem: palette.primary,
  heritage: palette.primary,
  nature: palette.success,
  reward: palette.primary,
};

export const lightTheme = {
  ...sharedTokens,
  background: palette.background,
  backgroundLight: palette.background,
  surface: palette.surface,
  surfaceSolid: palette.surface,
  surfaceLight: palette.background,
  card: palette.surface,
  cardLight: palette.background,
  glass: 'rgba(255, 255, 255, 0.92)',
  glassBorder: 'rgba(0, 0, 0, 0.12)',
  overlay: 'rgba(0, 0, 0, 0.45)',
  mapWater: '#A8C5D4',
  mapLand: '#E8D9C4',
  mapRoad: '#D4C4A8',
  mapRoute: palette.primary,
  backgroundSecondary: palette.background,
  surfaceElevated: palette.background,
  surfaceSoft: palette.primaryLight,
  surfaceHover: palette.background,
  cardHover: palette.background,
  textInverse: palette.surface,
  textLink: palette.primary,
  overlayLight: 'rgba(0, 0, 0, 0.2)',
  shadow: 'rgba(0, 0, 0, 0.08)',
  shadowMedium: 'rgba(0, 0, 0, 0.12)',
  shadowStrong: 'rgba(0, 0, 0, 0.18)',
  glow: 'rgba(0, 0, 0, 0.16)',
  gradient: {
    primary: [palette.primary, palette.primaryDark],
    primaryReverse: [palette.primaryDark, palette.primary],
    secondary: [palette.surface, palette.background],
    accent: [palette.primary, palette.primaryLight],
    gold: [palette.primary, palette.primaryLight],
    sunset: [palette.primaryDark, palette.primaryLight],
    ocean: [palette.primary, palette.primaryLight],
    dark: [palette.primaryDark, palette.text],
    cream: [palette.surface, palette.background, palette.surface],
  },
  water: '#A8C5D4',
  purpleGlow: 'rgba(0, 0, 0, 0.16)',
  goldGlow: 'rgba(0, 0, 0, 0.16)',
  cyanGlow: 'rgba(0, 0, 0, 0.16)',
  greenGlow: 'rgba(0, 0, 0, 0.18)',
} as const;

/** Dark media surfaces retain neutral contrast with black controls. */
export const darkTheme = {
  ...sharedTokens,
  secondary: palette.primaryLight,
  primarySoft: 'rgba(255, 255, 255, 0.10)',
  secondarySoft: 'rgba(255, 255, 255, 0.08)',
  successSoft: 'rgba(255, 255, 255, 0.10)',
  warningSoft: 'rgba(183, 121, 31, 0.18)',
  dangerSoft: 'rgba(201, 74, 74, 0.16)',
  background: '#000000',
  backgroundLight: '#121212',
  surface: '#121212',
  surfaceSolid: '#000000',
  surfaceLight: '#1C1C1E',
  card: '#121212',
  cardLight: '#1C1C1E',
  glass: 'rgba(0, 0, 0, 0.92)',
  glassBorder: 'rgba(255, 255, 255, 0.16)',
  text: '#FFFFFF',
  textSecondary: '#B3B3B3',
  textMuted: '#8E8E93',
  border: 'rgba(255, 255, 255, 0.2)',
  borderLight: 'rgba(255, 255, 255, 0.12)',
  borderSoft: 'rgba(255, 255, 255, 0.12)',
  borderFocus: palette.primaryLight,
  borderError: palette.error,
  overlay: 'rgba(0, 0, 0, 0.7)',
  overlayLight: 'rgba(0, 0, 0, 0.5)',
  backgroundSecondary: '#121212',
  surfaceElevated: '#1C1C1E',
  surfaceSoft: '#121212',
  surfaceHover: '#1C1C1E',
  cardHover: '#1C1C1E',
  textInverse: palette.text,
  textLink: palette.primaryLight,
  shadow: 'rgba(0, 0, 0, 0.4)',
  shadowMedium: 'rgba(0, 0, 0, 0.5)',
  shadowStrong: 'rgba(0, 0, 0, 0.6)',
  glow: 'rgba(255, 255, 255, 0.22)',
  gradient: {
    primary: [palette.primary, palette.primaryDark],
    primaryReverse: [palette.primaryDark, palette.primary],
    secondary: [palette.primaryLight, palette.primary],
    accent: [palette.primary, palette.primaryLight],
    gold: [palette.primary, palette.primaryLight],
    sunset: [palette.primaryDark, palette.primaryLight],
    ocean: [palette.primary, palette.primaryLight],
    dark: ['#000000', '#121212'],
    cream: ['#000000', '#121212', '#000000'],
  },
  mapWater: '#A8C5D4',
  mapLand: '#1A1A1A',
  mapRoad: '#1C1C1E',
  mapRoute: palette.primaryLight,
  water: '#A8C5D4',
  purpleGlow: 'rgba(255, 255, 255, 0.22)',
  goldGlow: 'rgba(255, 255, 255, 0.22)',
  cyanGlow: 'rgba(255, 255, 255, 0.22)',
  greenGlow: 'rgba(255, 255, 255, 0.22)',
} as const;

export type Theme = typeof lightTheme;

export const spacing = {
  xs: 4,
  sm: 8,
  md: 16,
  lg: 24,
  xl: 32,
  xxl: 48,
};

export const borderRadius = {
  sm: 8,
  md: 12,
  lg: 16,
  xl: 24,
  round: 50,
};

export const shadows = {
  sm: {
    shadowColor: 'rgba(0, 0, 0, 0.12)',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.18,
    shadowRadius: 4,
    elevation: 3,
  },
  md: {
    shadowColor: palette.primaryDark,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.16,
    shadowRadius: 8,
    elevation: 5,
  },
  lg: {
    shadowColor: palette.primaryDark,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.18,
    shadowRadius: 16,
    elevation: 8,
  },
  glow: {
    shadowColor: palette.primary,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.28,
    shadowRadius: 20,
    elevation: 10,
  },
};

export const colors = lightTheme;
