import type { TripPlan } from '../services/api/trips';

function formatOpeningHours(hours: unknown): string {
  if (!hours || typeof hours !== 'object') return '';
  const h = hours as Record<string, string>;
  const today = ['sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'][new Date().getDay()];
  return h[today] || h.daily || h.all || '';
}

/** Build a shareable plain-text itinerary (PDF apps can import from share sheet). */
export function buildTripExportText(trip: TripPlan): string {
  const lines: string[] = [
    `PalSafar Trip: ${trip.title || trip.destination}`,
    `Destination: ${trip.destination || '—'}`,
    `Days: ${trip.days} | Travelers: ${trip.travelers || 'SOLO'} | Budget: ${trip.budget || 'MEDIUM'}`,
    trip.totalDistance ? `Total distance: ${trip.totalDistance.toFixed(1)} km` : '',
    '',
  ].filter(Boolean);

  const days = [...(trip.tripDays || [])].sort((a, b) => a.dayNumber - b.dayNumber);
  for (const day of days) {
    lines.push(`--- Day ${day.dayNumber}${day.theme ? `: ${day.theme}` : ''} ---`);
    const stops = [...(day.stops || [])].sort((a, b) => a.order - b.order);
    if (stops.length === 0) {
      lines.push('  (no stops)');
      continue;
    }
    for (const stop of stops) {
      const p = stop.place;
      const time = stop.startTime && stop.endTime ? `${stop.startTime}–${stop.endTime}` : '';
      const fee = stop.entryFee != null ? (stop.entryFee <= 0 ? 'Free' : `₹${stop.entryFee}`) : '';
      const hours = formatOpeningHours(p?.openingHours);
      lines.push(`  ${stop.order + 1}. ${p?.name || 'Place'}`);
      if (time) lines.push(`     Time: ${time} (${stop.duration || '?'} min)`);
      if (p?.category) lines.push(`     Category: ${p.category}`);
      if (p?.rating) lines.push(`     Rating: ${p.rating}/5`);
      if (fee) lines.push(`     Entry: ${fee}`);
      if (hours) lines.push(`     Hours: ${hours}`);
      if (stop.distanceFromPrev) lines.push(`     From prev: ${stop.distanceFromPrev.toFixed(1)} km`);
      if (stop.reason) lines.push(`     Why: ${stop.reason}`);
      lines.push('');
    }
  }

  lines.push('Generated by PalSafar — all places verified from our database.');
  return lines.join('\n');
}
